spring.application.name=project.security

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

# Enables the DATA.SQL for DATABASE
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update

# PostgreSQL Configuration (Port 5444)
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5444/security
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true


server.port:8089